### ISSUE TITLE
install.sh silent output could cause confusion

### ISSUE THREAD

**Issue by falkyre** [sflems/nhl-led-scoreboard-webgui#1]
Just doing the install to test out now.  One thing I'd suggest to to allow the pip3 install -r requirements.txt to actually output to the terminal rather than to the webgui-log.out file so users have some form of notification that the install is running.  With the output to the log file, the install appears to the end user as if it's hung.  There's no real indication of what's going on.

Once it hits this line
`Touching .secret.txt and updating permissions...`
Maybe add that the python requirements are being installed and it may take some time for the install.

**Comment by sflems** [comment]
Great idea! It does kind of go silent during that step.

I'd certainly like to expand on the install script with confirmation/error messages for each step, but I'm still drilling down the bash logging basics. It's on the to-do list!
